# check token generation
POST http://localhost:5050/auth/login
Content-Type: application/json

{
    "user":"rasheedha",
    "pass":"mohamed@123"
}
###
GET http://localhost:5050/course/
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhc2hlZWRoYSIsImlhdCI6MTczODY4NzA0MiwiZXhwIjoxNzM4NjkwNjQyfQ.jUzDlUkqzz9VN9FmvYTl45C2OagqZmZsNjjk_lkC3XU
###
GET http://localhost:5050/expert/
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhc2hlZWRoYSIsImlhdCI6MTczODY4NzA0MiwiZXhwIjoxNzM4NjkwNjQyfQ.jUzDlUkqzz9VN9FmvYTl45C2OagqZmZsNjjk_lkC3XU
###
GET http://localhost:5050/expert/experience/11
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhc2hlZWRoYSIsImlhdCI6MTczODY4NzA0MiwiZXhwIjoxNzM4NjkwNjQyfQ.jUzDlUkqzz9VN9FmvYTl45C2OagqZmZsNjjk_lkC3XU