# check token generation
POST http://localhost:5050/auth/login
Content-Type: application/json

{
    "user":"rasheedha",
    "pass":"mohamed@123"
}
###
GET http://localhost:5050/course/
###
GET http://localhost:5050/expert/