# check token generation
POST http://localhost:5050/auth/login
Content-Type: application/json

{
    "user":"rasheedha",
    "pass":"mohamed@123"
}
###
GET http://localhost:5050/course/
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhc2hlZWRoYSIsImlhdCI6MTczODY3OTU3NCwiZXhwIjoxNzM4NjgzMTc0fQ.twHmDqx6imOSH3lwA6vK2mysNyBt6VqkWaSP3H-8jvg
###
GET http://localhost:5050/expert/
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhc2hlZWRoYSIsImlhdCI6MTczODY3OTU3NCwiZXhwIjoxNzM4NjgzMTc0fQ.twHmDqx6imOSH3lwA6vK2mysNyBt6VqkWaSP3H-8jvg
###
GET http://localhost:5050/expert/experience/11
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhc2hlZWRoYSIsImlhdCI6MTczODY3OTgxMSwiZXhwIjoxNzM4NjgzNDExfQ.XOprsBXKqE8yO6U1oIm-H0c8ik_SqsY0S3RTaiUlefY